[package]
name = "eternalreckoning-protocol"
version = "0.1.0"
authors = ["Henry Carlson <henry.carlson@gmail.com>"]
edition = "2018"

[features]
default = ["bitflags"]

net = []

[dependencies]
bitflags = { version = "1.2.1", optional = true }
bytes = "~0.5"